# Generated by Django 4.2.14 on 2024-08-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
